"""phase 2 job discovery

Revision ID: a1447d61a96d
Revises: a84091e127dd
Create Date: 2026-10-05 23:54:56.006518
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'a1447d61a96d'
down_revision: str | None = 'a84091e127dd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_companies_ats_board', 'companies', ['ats_type', 'ats_token'], unique=True, postgresql_where=sa.text('ats_token IS NOT NULL'))
    op.add_column('jobs', sa.Column('source_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index('ix_jobs_active_effective_date', 'jobs', ['is_active', sa.literal_column('coalesce(posted_at, first_seen_at)')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jobs_active_effective_date', table_name='jobs')
    op.drop_column('jobs', 'source_meta')
    op.drop_index('uq_companies_ats_board', table_name='companies', postgresql_where=sa.text('ats_token IS NOT NULL'))
    # ### end Alembic commands ###
