"""initial schema

Revision ID: a84091e127dd
Revises:
Create Date: 2026-10-04 01:53:47.862028
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision: str = "a84091e127dd"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "allowed_emails",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_allowed_emails")),
        sa.UniqueConstraint("email", name=op.f("uq_allowed_emails_email")),
    )
    op.create_table(
        "companies",
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=True),
        sa.Column(
            "ats_type",
            sa.Enum(
                "greenhouse",
                "lever",
                "ashby",
                "none",
                name="ats_type",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            server_default="none",
            nullable=False,
        ),
        sa.Column("ats_token", sa.String(length=255), nullable=True),
        sa.Column(
            "size_hint",
            sa.Enum(
                "startup",
                "mid",
                "large",
                "unknown",
                name="size_hint",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            server_default="unknown",
            nullable=False,
        ),
        sa.Column("employee_count", sa.Integer(), nullable=True),
        sa.Column("industry", sa.String(length=200), nullable=True),
        sa.Column("hq_location", sa.String(length=200), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("website_text", sa.Text(), nullable=True),
        sa.Column("website_fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True
        ),
        sa.Column("last_polled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "ats_type IN ('greenhouse', 'lever', 'ashby', 'none')",
            name=op.f("ck_companies_ats_type"),
        ),
        sa.CheckConstraint(
            "size_hint IN ('startup', 'mid', 'large', 'unknown')",
            name=op.f("ck_companies_size_hint"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
        sa.UniqueConstraint("domain", name=op.f("uq_companies_domain")),
    )
    op.create_table(
        "suppression_list",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column(
            "reason",
            sa.Enum(
                "opt_out",
                "bounce",
                "manual",
                name="suppression_reason",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "reason IN ('opt_out', 'bounce', 'manual')",
            name=op.f("ck_suppression_list_suppression_reason"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suppression_list")),
        sa.UniqueConstraint("email", name=op.f("uq_suppression_list_email")),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("name", sa.String(length=200), server_default="", nullable=False),
        sa.Column(
            "is_admin", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "timezone",
            sa.String(length=64),
            server_default="Asia/Kolkata",
            nullable=False,
        ),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "contacts",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("full_name", sa.String(length=300), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column(
            "email_source",
            sa.Enum(
                "hunter",
                "apollo",
                "manual",
                "pattern",
                name="email_source",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "verification_status",
            sa.Enum(
                "valid",
                "accept_all",
                "unknown",
                "invalid",
                name="verification_status",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            server_default="unknown",
            nullable=False,
        ),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "role_category",
            sa.Enum(
                "founder",
                "eng_manager",
                "engineer",
                "recruiter",
                "other",
                name="role_category",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            server_default="other",
            nullable=False,
        ),
        sa.Column("last_contacted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "email_source IN ('hunter', 'apollo', 'manual', 'pattern')",
            name=op.f("ck_contacts_email_source"),
        ),
        sa.CheckConstraint(
            "role_category IN ('founder', 'eng_manager', 'engineer', 'recruiter', 'other')",
            name=op.f("ck_contacts_role_category"),
        ),
        sa.CheckConstraint(
            "verification_status IN ('valid', 'accept_all', 'unknown', 'invalid')",
            name=op.f("ck_contacts_verification_status"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_contacts_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contacts")),
        sa.UniqueConstraint("email", name=op.f("uq_contacts_email")),
    )
    op.create_index(
        op.f("ix_contacts_company_id"), "contacts", ["company_id"], unique=False
    )
    op.create_table(
        "jobs",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "greenhouse",
                "lever",
                "ashby",
                "adzuna",
                "hn",
                "manual",
                name="job_source",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("location", sa.String(length=300), nullable=True),
        sa.Column("remote", sa.Boolean(), nullable=True),
        sa.Column("employment_type", sa.String(length=32), nullable=True),
        sa.Column("description_text", sa.Text(), server_default="", nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("missed_polls", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("dedupe_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True
        ),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('greenhouse', 'lever', 'ashby', 'adzuna', 'hn', 'manual')",
            name=op.f("ck_jobs_job_source"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_jobs_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("dedupe_hash", name=op.f("uq_jobs_dedupe_hash")),
    )
    op.create_index(op.f("ix_jobs_company_id"), "jobs", ["company_id"], unique=False)
    op.create_index(
        "ix_jobs_source_external_id", "jobs", ["source", "external_id"], unique=False
    )
    op.create_table(
        "master_resumes",
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "is_current", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("source_file_path", sa.Text(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_master_resumes_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_master_resumes")),
        sa.UniqueConstraint(
            "user_id", "version", name="uq_master_resumes_user_version"
        ),
    )
    op.create_index(
        op.f("ix_master_resumes_user_id"), "master_resumes", ["user_id"], unique=False
    )
    op.create_index(
        "uq_master_resumes_one_current",
        "master_resumes",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("is_current"),
    )
    op.create_table(
        "oauth_tokens",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum(
                "google",
                name="oauth_provider",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("encrypted_refresh_token", sa.Text(), nullable=False),
        sa.Column("scopes", sa.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "needs_reauth",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "provider IN ('google')", name=op.f("ck_oauth_tokens_oauth_provider")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_oauth_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_oauth_tokens")),
        sa.UniqueConstraint("user_id", name=op.f("uq_oauth_tokens_user_id")),
    )
    op.create_table(
        "prospect_targets",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "contact_titles", sa.ARRAY(sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "industries", sa.ARRAY(sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "locations", sa.ARRAY(sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "company_sizes", sa.ARRAY(sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "include_companies",
            sa.ARRAY(sa.UUID()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "exclude_companies",
            sa.ARRAY(sa.UUID()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_prospect_targets_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prospect_targets")),
    )
    op.create_index(
        op.f("ix_prospect_targets_user_id"),
        "prospect_targets",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "usage_ledger",
        sa.Column(
            "provider",
            sa.Enum(
                "gemini",
                "anthropic",
                "hunter",
                "apollo",
                "adzuna",
                name="usage_provider",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("operation", sa.String(length=100), nullable=False),
        sa.Column("units", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "est_cost_usd",
            sa.Numeric(precision=10, scale=6),
            server_default="0",
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "provider IN ('gemini', 'anthropic', 'hunter', 'apollo', 'adzuna')",
            name=op.f("ck_usage_ledger_usage_provider"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_usage_ledger_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_ledger")),
    )
    op.create_index(
        op.f("ix_usage_ledger_user_id"), "usage_ledger", ["user_id"], unique=False
    )
    op.create_table(
        "user_company_blocks",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_user_company_blocks_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_company_blocks_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_company_blocks")),
        sa.UniqueConstraint(
            "user_id", "company_id", name="uq_user_company_blocks_user_company"
        ),
    )
    op.create_index(
        op.f("ix_user_company_blocks_company_id"),
        "user_company_blocks",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_company_blocks_user_id"),
        "user_company_blocks",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "user_llm_keys",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum(
                "gemini",
                "anthropic",
                name="llm_provider",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("encrypted_api_key", sa.Text(), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_quota_exhausted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "provider IN ('gemini', 'anthropic')",
            name=op.f("ck_user_llm_keys_llm_provider"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_llm_keys_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_llm_keys")),
        sa.UniqueConstraint("user_id", name=op.f("uq_user_llm_keys_user_id")),
    )
    op.create_table(
        "user_preferences",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "target_roles", sa.ARRAY(sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "employment_types", sa.ARRAY(sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "locations", sa.ARRAY(sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "remote_ok", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "company_stages", sa.ARRAY(sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("min_fit_score", sa.Integer(), server_default="70", nullable=False),
        sa.Column(
            "max_job_age_days", sa.Integer(), server_default="14", nullable=False
        ),
        sa.Column(
            "daily_draft_batch", sa.Integer(), server_default="8", nullable=False
        ),
        sa.Column(
            "open_outreach_share", sa.Integer(), server_default="40", nullable=False
        ),
        sa.Column("daily_send_cap", sa.Integer(), server_default="15", nullable=False),
        sa.Column(
            "followup_after_days", sa.Integer(), server_default="6", nullable=False
        ),
        sa.Column(
            "send_window_start",
            sa.Time(),
            server_default=sa.text("'09:30'"),
            nullable=False,
        ),
        sa.Column(
            "send_window_end",
            sa.Time(),
            server_default=sa.text("'18:00'"),
            nullable=False,
        ),
        sa.Column(
            "paused", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("about_me", sa.String(length=300), server_default="", nullable=False),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "daily_draft_batch >= 0",
            name=op.f("ck_user_preferences_daily_draft_batch_nonneg"),
        ),
        sa.CheckConstraint(
            "daily_send_cap BETWEEN 0 AND 30",
            name=op.f("ck_user_preferences_daily_send_cap_range"),
        ),
        sa.CheckConstraint(
            "followup_after_days > 0",
            name=op.f("ck_user_preferences_followup_after_days_positive"),
        ),
        sa.CheckConstraint(
            "max_job_age_days > 0",
            name=op.f("ck_user_preferences_max_job_age_days_positive"),
        ),
        sa.CheckConstraint(
            "min_fit_score BETWEEN 0 AND 100",
            name=op.f("ck_user_preferences_min_fit_score_range"),
        ),
        sa.CheckConstraint(
            "open_outreach_share BETWEEN 0 AND 100",
            name=op.f("ck_user_preferences_open_outreach_share_range"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_preferences_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_preferences")),
        sa.UniqueConstraint("user_id", name=op.f("uq_user_preferences_user_id")),
    )
    op.create_table(
        "company_matches",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("prospect_target_id", sa.Uuid(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("reasoning", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "new",
                "queued",
                "contacted",
                "hidden",
                name="company_match_status",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            server_default="new",
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('new', 'queued', 'contacted', 'hidden')",
            name=op.f("ck_company_matches_company_match_status"),
        ),
        sa.CheckConstraint(
            "score BETWEEN 0 AND 100", name=op.f("ck_company_matches_score_range")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_company_matches_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["prospect_target_id"],
            ["prospect_targets.id"],
            name=op.f("fk_company_matches_prospect_target_id_prospect_targets"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_company_matches_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company_matches")),
        sa.UniqueConstraint(
            "user_id", "company_id", name="uq_company_matches_user_company"
        ),
    )
    op.create_index(
        op.f("ix_company_matches_company_id"),
        "company_matches",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_company_matches_prospect_target_id"),
        "company_matches",
        ["prospect_target_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_company_matches_user_id"), "company_matches", ["user_id"], unique=False
    )
    op.create_table(
        "job_matches",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("embedding_score", sa.Float(), nullable=True),
        sa.Column("llm_score", sa.Integer(), nullable=True),
        sa.Column(
            "matched_skills", sa.ARRAY(sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "missing_skills", sa.ARRAY(sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("reasoning", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "new",
                "shortlisted",
                "hidden",
                "in_pipeline",
                "expired",
                name="job_match_status",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            server_default="new",
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('new', 'shortlisted', 'hidden', 'in_pipeline', 'expired')",
            name=op.f("ck_job_matches_job_match_status"),
        ),
        sa.CheckConstraint(
            "llm_score IS NULL OR llm_score BETWEEN 0 AND 100",
            name=op.f("ck_job_matches_llm_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            name=op.f("fk_job_matches_job_id_jobs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_job_matches_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_matches")),
        sa.UniqueConstraint("user_id", "job_id", name="uq_job_matches_user_job"),
    )
    op.create_index(
        op.f("ix_job_matches_job_id"), "job_matches", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_job_matches_user_id"), "job_matches", ["user_id"], unique=False
    )
    op.create_table(
        "outreach",
        sa.Column(
            "campaign_type",
            sa.Enum(
                "job",
                "open",
                name="campaign_type",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("company_match_id", sa.Uuid(), nullable=True),
        sa.Column("contact_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "drafting",
                "pending_review",
                "approved",
                "scheduled",
                "sent",
                "replied",
                "followup_due",
                "send_failed",
                "skipped",
                "failed",
                "closed",
                name="outreach_status",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            server_default="drafting",
            nullable=False,
        ),
        sa.Column("subject", sa.String(length=200), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column(
            "tailored_resume", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("resume_pdf_path", sa.Text(), nullable=True),
        sa.Column(
            "resume_diff", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "ats_keyword_coverage",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("personalization_source", sa.Text(), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("gmail_message_id", sa.String(length=255), nullable=True),
        sa.Column("gmail_thread_id", sa.String(length=255), nullable=True),
        sa.Column("replied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("followup_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "outcome",
            sa.Enum(
                "none",
                "referred",
                "interview",
                "rejected",
                "not_hiring",
                name="outcome",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            server_default="none",
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), server_default="", nullable=False),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "campaign_type <> 'job' OR job_id IS NOT NULL",
            name=op.f("ck_outreach_job_campaign_has_job"),
        ),
        sa.CheckConstraint(
            "campaign_type IN ('job', 'open')", name=op.f("ck_outreach_campaign_type")
        ),
        sa.CheckConstraint(
            "outcome IN ('none', 'referred', 'interview', 'rejected', 'not_hiring')",
            name=op.f("ck_outreach_outcome"),
        ),
        sa.CheckConstraint(
            "status IN ('drafting', 'pending_review', 'approved', 'scheduled', 'sent', 'replied', 'followup_due', 'send_failed', 'skipped', 'failed', 'closed')",
            name=op.f("ck_outreach_outreach_status"),
        ),
        sa.CheckConstraint(
            "followup_count BETWEEN 0 AND 1",
            name=op.f("ck_outreach_followup_count_max_one"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_outreach_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["company_match_id"],
            ["company_matches.id"],
            name=op.f("fk_outreach_company_match_id_company_matches"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
            name=op.f("fk_outreach_contact_id_contacts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            name=op.f("fk_outreach_job_id_jobs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_outreach_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outreach")),
    )
    op.create_index(
        op.f("ix_outreach_company_id"), "outreach", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_outreach_company_match_id"),
        "outreach",
        ["company_match_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outreach_contact_id"), "outreach", ["contact_id"], unique=False
    )
    op.create_index(op.f("ix_outreach_job_id"), "outreach", ["job_id"], unique=False)
    op.create_index(op.f("ix_outreach_status"), "outreach", ["status"], unique=False)
    op.create_index(op.f("ix_outreach_user_id"), "outreach", ["user_id"], unique=False)
    op.create_index(
        "uq_outreach_one_active_per_company",
        "outreach",
        ["user_id", "company_id"],
        unique=True,
        postgresql_where=sa.text("status NOT IN ('closed', 'skipped', 'failed')"),
    )
    op.create_table(
        "outreach_events",
        sa.Column("outreach_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "drafted",
                "edited",
                "regenerated",
                "approved",
                "skipped",
                "scheduled",
                "sent",
                "send_failed",
                "reply_detected",
                "followup_drafted",
                "followup_sent",
                "bounced",
                "closed",
                "outcome_set",
                "upgraded_to_job",
                name="outreach_event_type",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "type IN ('drafted', 'edited', 'regenerated', 'approved', 'skipped', 'scheduled', 'sent', 'send_failed', 'reply_detected', 'followup_drafted', 'followup_sent', 'bounced', 'closed', 'outcome_set', 'upgraded_to_job')",
            name=op.f("ck_outreach_events_outreach_event_type"),
        ),
        sa.ForeignKeyConstraint(
            ["outreach_id"],
            ["outreach.id"],
            name=op.f("fk_outreach_events_outreach_id_outreach"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_outreach_events_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outreach_events")),
    )
    op.create_index(
        op.f("ix_outreach_events_outreach_id"),
        "outreach_events",
        ["outreach_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outreach_events_user_id"), "outreach_events", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_outreach_events_user_id"), table_name="outreach_events")
    op.drop_index(op.f("ix_outreach_events_outreach_id"), table_name="outreach_events")
    op.drop_table("outreach_events")
    op.drop_index(
        "uq_outreach_one_active_per_company",
        table_name="outreach",
        postgresql_where=sa.text("status NOT IN ('closed', 'skipped', 'failed')"),
    )
    op.drop_index(op.f("ix_outreach_user_id"), table_name="outreach")
    op.drop_index(op.f("ix_outreach_status"), table_name="outreach")
    op.drop_index(op.f("ix_outreach_job_id"), table_name="outreach")
    op.drop_index(op.f("ix_outreach_contact_id"), table_name="outreach")
    op.drop_index(op.f("ix_outreach_company_match_id"), table_name="outreach")
    op.drop_index(op.f("ix_outreach_company_id"), table_name="outreach")
    op.drop_table("outreach")
    op.drop_index(op.f("ix_job_matches_user_id"), table_name="job_matches")
    op.drop_index(op.f("ix_job_matches_job_id"), table_name="job_matches")
    op.drop_table("job_matches")
    op.drop_index(op.f("ix_company_matches_user_id"), table_name="company_matches")
    op.drop_index(
        op.f("ix_company_matches_prospect_target_id"), table_name="company_matches"
    )
    op.drop_index(op.f("ix_company_matches_company_id"), table_name="company_matches")
    op.drop_table("company_matches")
    op.drop_table("user_preferences")
    op.drop_table("user_llm_keys")
    op.drop_index(
        op.f("ix_user_company_blocks_user_id"), table_name="user_company_blocks"
    )
    op.drop_index(
        op.f("ix_user_company_blocks_company_id"), table_name="user_company_blocks"
    )
    op.drop_table("user_company_blocks")
    op.drop_index(op.f("ix_usage_ledger_user_id"), table_name="usage_ledger")
    op.drop_table("usage_ledger")
    op.drop_index(op.f("ix_prospect_targets_user_id"), table_name="prospect_targets")
    op.drop_table("prospect_targets")
    op.drop_table("oauth_tokens")
    op.drop_index(
        "uq_master_resumes_one_current",
        table_name="master_resumes",
        postgresql_where=sa.text("is_current"),
    )
    op.drop_index(op.f("ix_master_resumes_user_id"), table_name="master_resumes")
    op.drop_table("master_resumes")
    op.drop_index("ix_jobs_source_external_id", table_name="jobs")
    op.drop_index(op.f("ix_jobs_company_id"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_contacts_company_id"), table_name="contacts")
    op.drop_table("contacts")
    op.drop_table("users")
    op.drop_table("suppression_list")
    op.drop_table("companies")
    op.drop_table("allowed_emails")
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS vector")
